### ISSUE TITLE
PROFILE: Weird icon appears in Profile

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#447] opened 2023-11-27 16:22 UTC
**What is the problem?**
Upon making the Organisation field active, a weird icon appears in the right corner.

https://github.com/citizenos/citizenos-fe/assets/34126353/40fab30d-b42f-439d-a0e7-088c5f19f909

**Comment by ilmartyrk** [comment] 2023-12-21 23:00
@oksks is this still an issue, I cannot reproduce that, maybe @ssin1901 can check if she can get it to appear too on Safari

**Comment by ssin1901** [comment] 2024-02-01 12:29
@oksks @ilmartyrk could not replicate on Safari either. Everything seems to be in order with Profile

Closing for now.

<img width="1215" alt="Screenshot 2024-02-01 at 14 27 16" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ac62d270-6ac3-4697-bc08-9a1fec4ca699">

**Closed as completed by ssin1901** 2024-02-01 12:29 UTC
Labels: bug, Redesign
