### ISSUE TITLE
Profile: Pic uploads squished and blurry

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#888] opened 2024-02-22 19:21 UTC
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/71b9343b-6d36-4f16-ac80-36340c0f1ef5)

**Comment by ilmartyrk** [comment] 2024-02-22 20:41
@BeccaMelhuish closing as it is duplicate of https://github.com/citizenos/citizenos-fe/issues/536

**Closed as completed by ilmartyrk** 2024-02-22 20:41 UTC
Labels: bug, Redesign
