### ISSUE TITLE
IDEA GATHERING: Can't add topic text (says "authentication required" while I'm logged in)

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#1423] opened 2024-07-18 13:15 UTC
**What is the problem?**
Creating a sample idea gathering, I've tried to add topic text and the app doesn't allow me. It shows two texts overlaying one another and I can't enter text:

<img width="1114" alt="Screenshot 2024-07-18 at 16 07 18" src="https://github.com/user-attachments/assets/64a08745-0d4d-4f2b-a8d9-f488fa17589e">

Mac, latest version of Chrome. Before I arrived back at the "Compose" tab, I've clicked through all other tabs to screenshot them for Crowdin.

**Comment by BeccaMelhuish** [comment] 2024-07-24 11:42
@ilmartyrk FYI, first (idea gathering) topic I tried to create on live, I got this one too:

![image](https://github.com/user-attachments/assets/f5372ea7-f000-4e41-ad89-eb3f7f7e9a5f)

**Comment by ilmartyrk** [comment] 2024-07-24 11:52
Yes, I am still not sure what is causing this. I started updating Etherpad on my local machine, but it needs some more work as it's plugin system has changed. And to make the new version work together with our API as intended.

**Comment by BeccaMelhuish** [comment] 2024-07-24 11:54
Also just FYI, when I published then went back in to edit it, worked fine (as often seems to happen, though not 100% of the time) :)

**Comment by ilmartyrk** [comment] 2024-07-24 21:22
@BeccaMelhuish @oksks @ssin1901 I've updated Etherpad on our test platform. As it is a complete new version and it took some time to get it up and running, I think we need some testing to see if any errors pop up or any new weird behaviors

**Comment by ilmartyrk** [comment] 2024-07-24 21:33
Closing as duplicate of https://github.com/citizenos/citizenos-fe/issues/364

**Closed as completed by ilmartyrk** 2024-07-24 21:33 UTC
Labels: bug, high-priority, test app
