### ISSUE TITLE
TOPIC: Add Group to Topic view keeps changing

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1502] opened 2024-08-21 08:18 UTC
**What is the problem?**
_Tested in Google Chrome in incognito mode_

The _Add Group to Topic_ view keeps changing. It displayed correctly for the first topic (screenshot1) but now displays incorrectly (screenshot2) for a different topic.

<img width="1037" alt="Screenshot 2024-08-21 at 10 58 21" src="https://github.com/user-attachments/assets/87b135fe-08ef-40dd-a2b9-10ffc6dfa21a">

<img width="1350" alt="Screenshot 2024-08-21 at 10 56 31" src="https://github.com/user-attachments/assets/d5432c6d-6971-48fb-8901-10845d6a17c3">

NB! Seems related to #1493 

**Why is this a problem?**
High priority. Users cannot add groups to topics,  and the different views will also confuse the users

**Possible solution.**
View should be correctly displayed

**Comment by ilmartyrk** [comment] 2024-08-21 09:58
@ssin1901 duplicate of https://github.com/citizenos/citizenos-fe/issues/1493

**Closed as completed by ilmartyrk** 2024-08-21 09:58 UTC
Labels: bug, high-priority
