### ISSUE TITLE
Ideation: 'Choose from ideas' shouldn't be offered in a discussion topic vote. 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1145] opened 2024-05-06 15:03 UTC
If you are in a discussion topic (no ideation) and you start a vote, you are given the option to "Choose from ideas", as if it was an ideation topic. This option should only appear if it's an ideation topic (or a topic with an ideation phase, at least). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8b055224-3794-4284-8a12-30e8297bfc99)

**Comment by ssin1901** [comment] 2024-05-06 21:03
@BeccaMelhuish seems to be a duplicate of #1130

**Comment by ilmartyrk** [comment] 2024-05-08 09:37
@BeccaMelhuish  @ssin1901 closing as it is duplicate

**Closed as completed by ilmartyrk** 2024-05-08 09:37 UTC
Labels: bug
