### ISSUE TITLE
TOPICS: Problems with editors rights to edit topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1554] opened 2024-09-04 12:50 UTC
I went into a topic to see what I could edit with editor rights. It seemed like I could edit everything, as all through the create flow (Compose, Settings, Idea gathering) I was able to edit things. But then when I clicked 'Save changes & publish'. I was told a this point that I don't have permissions. But then, it's unclear which of the things I changed in the 3 different tabs I didn't have permission to change. 

Needs to be clearer to editors what they can't edit. I.e. if they don't have rights to edit certain things, then they should be greyed out? @kevincrepin what would you advise? 

![image](https://github.com/user-attachments/assets/b308a8fd-34a7-407d-b266-770c3e49cc05)

**Comment by BeccaMelhuish** [comment] 2024-09-04 13:04
After trying some more, it seems that editors are being told they can't edit anything, but actually the things that they are able to edit are being saved. 

E.g. as editor I go in and edit any of these things: topic title, intro, topic text, header image, attachments, categories, language, country. For any of these edits, I'm told 'Insufficient permissions' so have to 'interrupt process'. But once I've interrupted the process, I find that actually the edits have been saved. Which is a problem both with being misinformed that I can't edit them, and also because 'Interrupt process' is meant to not save changes. 

If I go in and edit the idea gathering question and the deadline, the same thing happens, but when I 'interrupt process' and go to the topic, those changes haven't been saved - so I guess they are things which editors can't edit. 

@ssin1901 I won't add high priority tag for now, but you could investigate and see what you think?

**Comment by BeccaMelhuish** [comment] 2024-09-24 12:51
See this now closed issue here too: https://github.com/citizenos/citizenos-fe/issues/1593

**Comment by BeccaMelhuish** [comment] 2024-09-26 07:19
@ilmartyrk @ssin1901 moving to 'soon'

**Comment by BeccaMelhuish** [comment] 2024-09-27 10:33
Adding high priority label as seems it's a recurring bug, and when I tried it just now, my edits to the topic text weren't saved when I went into the topic after being told I had insufficient permissions. All the other changes were saved, but not the topic text field. 

See screen recording here: 

https://www.loom.com/share/677006730c7947769d1043a730028b74?sid=d6d478ab-17bf-4875-a10f-cf5b46a77ebc

Also, I was able to access the settings tab, which I shouldn't be able to as an editor, and should get the "Settings are locked" pop-up. @ssin1901 will make a [separate issue](https://github.com/citizenos/citizenos-fe/issues/1614) for this, but has said that they are locked (as they should be in discussion topics). It's just in idea gathering topics that they are unlocked.

![image](https://github.com/user-attachments/assets/557da421-055b-4259-91ee-e7db5d377541)

@ilmartyrk @ssin1901 will move this into ideation project in case it's possible to fix before Ilmar's off, seems fairly important (though number of users using editor rights is fairly low I understand?)

**Comment by BeccaMelhuish** [comment] 2024-09-27 10:37
Mentioning this issue here too in case connected: https://github.com/citizenos/citizenos-fe/issues/1613

Also @ssin1901 just confirmed that this 'insufficient permissions' error happens in discussion topics as well as idea gathering topics (so maybe isn't related to the settings being visible to edit in idea gathering topics).

**Comment by BeccaMelhuish** [comment] 2024-09-27 11:00
@ilmartyrk @ssin1901 Have realised we'll also have to add this 'Settings are locked' view for the 'idea gathering' tab, where the idea gathering setting are, e.g. here:

![image](https://github.com/user-attachments/assets/004c84b6-4c34-4528-a30c-823f9c876205)

**Comment by ssin1901** [comment] 2024-09-27 17:28
@ilmartyrk In test, the view is correct (see screen recording) but the insufficient permissions message prevents the user from successfully publishing the edits, though the edits are in fact saved.

https://github.com/user-attachments/assets/0f63430a-7b1d-4e5a-9fba-9a720797a488

**Comment by ilmartyrk** [comment] 2024-09-27 17:51
@ssin1901 found another item causing this error, should be fixed now for all edit views

**Comment by ssin1901** [comment] 2024-09-27 20:23
@ilmartyrk view is correct but save&publish not working as intended (see screen recording)

https://github.com/user-attachments/assets/5ecad9b7-a76e-43e4-99d3-d92fe7d209d7

**Comment by ilmartyrk** [comment] 2024-09-28 10:16
@ssin1901 posted a fix

**Closed as completed by ilmartyrk** 2024-09-28 10:16 UTC
Labels: bug, UX, high-priority

**Comment by ssin1901** [comment] 2024-09-28 14:12
Fixed and moving to Done (see screen recording)

https://github.com/user-attachments/assets/35310cbc-b6b1-47f9-9f68-51a5cbfc7e1a
