### ISSUE TITLE
Topic: Attachments 'add' button in the wrong place?  

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#712] opened 2024-01-30 09:50 UTC
@ilmartyrk @kevincrepin I can't tell if this 'Add' button has moved or I'm just not remembering how it has been already (and I don't see it in the designs), so just to check - is it in the right place? Feels wrong to me :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/0bb5c21c-6480-4ac4-aa5f-a57191f46f84)

**Comment by kevincrepin** [comment] 2024-01-31 08:24
We moved it there because previously there was just a 3 dot button on the far right side and people missed this. So we decided to add the label and place it next to the attachments title.

It's not what was originally designed, but at least this way people won't miss it.

**Comment by ilmartyrk** [comment] 2024-01-31 21:06
Closing as this is not a bug

**Closed as completed by ilmartyrk** 2024-01-31 21:06 UTC
Labels: bug, Redesign
