### ISSUE TITLE
Topic: Insufficient permissions trying to edit topic text as an editor 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1008] opened 2024-03-14 13:08 UTC
I got this when trying to edit topic text as an editor. But then when I went to the topic my edits were there. 

My flow was this: Edit topic, click continue, get taken through to settings and told I can't edit settings, go back to the compose tab via the pop-up, click save changes, get the error, click the X, see that the edits are saved anyway. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3d178c7d-09b9-4329-a643-d62a185072d3)

**Comment by ilmartyrk** [comment] 2024-03-14 23:20
@BeccaMelhuish I am quite sure that this issue was caused by the same issue that sent out too many invite to topic in group, so closing this issue

**Closed as completed by ilmartyrk** 2024-03-14 23:20 UTC
Labels: bug, Redesign
