### ISSUE TITLE
IDEATION: Internal Server Error when reporting own idea

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1278] opened 2024-06-03 18:35 UTC
I guess probably just as it was her own one, but user was testing out reporting (on her own idea) and got this error:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/be043492-19d5-4112-b96b-64e25ab36e74)

**Comment by ilmartyrk** [comment] 2024-06-04 08:21
Duplicate of https://github.com/citizenos/citizenos-fe/issues/1191

**Closed as completed by ilmartyrk** 2024-06-04 08:21 UTC
Labels: bug, test app

**Comment by ilmartyrk** [comment] 2024-06-04 08:22
@BeccaMelhuish can you provide more info under #1191, eg. when was this test done so I can check if it is a missing translation error something else
