### ISSUE TITLE
Discussion: When post an empty reply, get told it is too long

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#996] opened 2024-03-14 11:55 UTC
Tried posting a reply with no characters input, got this message:
(Presumably won't often happen though, so low priority)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/52bedfd6-f6b9-45d7-9874-7f967e686159)

**Comment by ilmartyrk** [comment] 2024-03-20 10:44
Duplicate of https://github.com/citizenos/citizenos-fe/issues/194, will use copy text from there https://github.com/citizenos/citizenos-fe/issues/194

**Comment by ssin1901** [comment] 2024-04-22 14:25
@ilmartyrk @BeccaMelhuish the fix – button disabled until characters are inputted (screenshot1, screenshot2) seems to work. Please re-open if necessary.
<img width="1440" alt="Screenshot 2024-04-22 at 16 47 43" src="https://github.com/citizenos/citizenos-fe/assets/72747107/62b57187-85e9-41e8-8e8f-905263f547f9">
<img width="1439" alt="Screenshot 2024-04-22 at 16 47 53" src="https://github.com/citizenos/citizenos-fe/assets/72747107/22d1b3b7-c7ad-452f-9fd5-a8199ce0435e">

**Closed as completed by ssin1901** 2024-04-22 14:25 UTC
Labels: bug, Redesign
