### ISSUE TITLE
TOPIC: Heading one does not display in the correct size

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1207] opened 2024-05-17 13:59 UTC
**What is the problem?**
_Tested in Google Chrome incognito in our Test App_

Heading one in Etherpad (screenshot1) does not render correctly in Preview  OR published mode (screenshot2)
<img width="1120" alt="Screenshot 2024-05-17 at 16 55 13" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2a1b5f46-fb9b-4b75-8966-5f7074aa69fc">

<img width="1161" alt="Screenshot 2024-05-17 at 16 55 22" src="https://github.com/citizenos/citizenos-fe/assets/72747107/fd27bee1-880c-4faa-9b93-31b6c7e97bf1">

**Why is this a problem?**
Leads to incorrect formatting of documents, which frustrates users 

**Possible solution.**
Heading one should render correctly i.e match display in Etherpad

**Comment by ilmartyrk** [comment] 2024-09-17 14:42
closing as duplicate of https://github.com/citizenos/citizenos-fe/issues/1181

**Closed as completed by ilmartyrk** 2024-09-17 14:42 UTC
Labels: bug, grouped
