### ISSUE TITLE
Voting: Neutral and Veto boxes very hard to select and de-select

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#754] opened 2024-02-02 17:35 UTC
Had really problems trying to (in create topic flow) - many many clicks to try and get it to select or deselect :

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/22bb57f3-bf58-4860-971b-98ed397d439e)

**Comment by BeccaMelhuish** [comment] 2024-02-02 17:36
Also, selecting them adds bins to the vote options (and not neutral or veto): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8e4e0395-5ad7-4d49-8c3e-e529be39804c)

**Comment by BeccaMelhuish** [comment] 2024-02-02 17:39
And when you try typing Neutral, when you add the 'l', it turns into a bin: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7e172a49-191c-4c3c-9b4d-689923d2f50a)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7a963978-a1ad-44ff-8d3f-3acd441e2c3e)

**Comment by ssin1901** [comment] 2024-03-13 14:49
@BeccaMelhuish @ilmartyrk just tested with Android and Desktop and the issue is more or less resolved other than the neutral jumping. As it is a very specific use case, I am not closing the issue but rather removing the high priority label

https://github.com/citizenos/citizenos-fe/assets/72747107/d82949a5-c4c9-41cf-b17f-58586164629f

**Comment by ssin1901** [comment] 2024-03-27 15:16
@ilmartyrk tested and it seems logical that the user cannot input "Neutral" as the option already exists and has a specific functionality – to prevent the user from checking other options in multiple choice. I am closing it for now.

**Closed as completed by ssin1901** 2024-03-27 15:16 UTC
Labels: bug, Redesign
