### ISSUE TITLE
DISCSUSSION: Selecting 'con arguments' filter took me to 'Get the discussion started page'

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1689] opened 2024-11-25 09:44 UTC
**What is the problem?**
@ssin1901 In [this topic](https://app.citizenos.com/en/topics/24faaf16-f75f-4d4c-8e94-a7d47c2f9755?argumentId=b61549a1-c96d-4693-8224-bcd260413b8a_v0),  (@ilmartyrk does that link work for you, or you need an invite link?) when selecting 'con arguments' in the argument types filter, all the arguments disappeared as well as the filters, and the 'Get the discussion started' text appeared:
  
![image](https://github.com/user-attachments/assets/b8ccaeea-596e-48ae-b9a4-c089e7550944)

However, when I refreshed and tried again, the filters worked fine. Just for note, it wasn't the case that I'd left the tab inactive, I had just been refreshing it to see if a new argument had appeared, before I then tried filtering for con arguments.  

**Why is this a problem?**
There are 2 issues:
- That the filter didn't work (there were 'con' arguments present, it should have shown them).
- That the 'get the discussion' started page was shown when it had already been started. 

**Possible solution.**
Filter should work correctly every time. 

@ssin1901 what to do with this one, shall I put it to QA for you to test more thoroughly, seeing as it was seemingly just a temporary glitch? :)

**Comment by ssin1901** [comment] 2024-11-25 09:48
@BeccaMelhuish @ilmartyrk could replicate and this should be high priority in my opinion. In my case, while testing in incognito mode, all the arguments disappeared when I clicked on page 2 (see screen recording)

https://github.com/user-attachments/assets/8945f71c-ad11-4d6c-9ab1-339bd0272e35

**Comment by BeccaMelhuish** [comment] 2024-11-25 09:49
@ssin1901 Ah, it is quite likely I was on page 2 when I tried the filter, so I think this is where the problem must lie. Will put to ready for dev high priority, thank you!

**Comment by ssin1901** [comment] 2024-11-25 09:56
@BeccaMelhuish @ilmartyrk the issue is also present in Test (see screen recording) and is replicable with all older topics. Could replicate in Chrome and Safari.

https://github.com/user-attachments/assets/0bde2456-3557-43bb-aead-78f0ed02d574

**Comment by ssin1901** [comment] 2024-11-26 23:31
@ilmartyrk is this fix in development.app.citizenos.com? Still getting the get the incorrect view in app.citizenos.com and test.app.citizenos.com

**Comment by ssin1901** [comment] 2024-11-26 23:38
@ilmartyrk in Live, some topics with discussions show this view until they are refreshed. I also got the error while clicking on different pages of a topic but could not replicate the second time. 

https://github.com/user-attachments/assets/6390a203-ae2f-4862-9e32-d6201b7a1212

**Comment by BeccaMelhuish** [comment] 2024-11-27 09:04
@ssin1901 I think the fix so far should only have been in development app, as per the new planned flow? So if it's fixed there it can be moved to 'QA pre-live' with ready for live label :)

**Comment by ssin1901** [comment] 2024-11-27 09:17
Ah okay! Moving it to QA pre-live then.

**Comment by BeccaMelhuish** [comment] 2024-11-27 11:38
Awesome, and 'ready for live' right? Adding it on that assumption :)

**Comment by BeccaMelhuish** [comment] 2024-11-27 13:46
Moving to Done as it got merged to live

**Closed as completed** 2024-11-28 06:31 UTC
Labels: bug, high-priority
