### ISSUE TITLE
IDEATION: Co-creators summary box buggyness 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1260] opened 2024-05-31 14:12 UTC
In test, in ideation topic. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5a2c1fcd-fa4f-496a-83c8-ca6e5162a9a1)

**Comment by ilmartyrk** [comment] 2024-06-04 10:47
Duplicate of https://github.com/citizenos/citizenos-fe/issues/1266

**Closed as completed by ilmartyrk** 2024-06-04 10:47 UTC
Labels: bug
