### ISSUE TITLE
GROUPS: Remove the Bulk Actions button in groups? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1542] opened 2024-08-30 13:27 UTC
@ilmartyrk are we going to remove the Bulk Actions button? Currently it doesn't work in Group->Members as no user is being removed (see screenshot)

<img width="1405" alt="Screenshot 2024-02-04 at 17 20 14" src="https://github.com/citizenos/citizenos-fe/assets/72747107/79ed6c78-e8bd-4ac3-9f73-43a19077e7f0">

_Originally posted by @ssin1901 in https://github.com/citizenos/citizenos-fe/issues/568#issuecomment-1925793457_

**Comment by BeccaMelhuish** [comment] 2024-10-09 10:22
@ssin1901 should this one be a 'next?' issue? Or just soon? Have put it in next for now

**Comment by ssin1901** [comment] 2024-10-09 11:44
@BeccaMelhuish I think the issue is resolved (screenshot1). I will close it.
<img width="1284" alt="Screenshot 2024-10-09 at 14 41 35" src="https://github.com/user-attachments/assets/e7462333-4858-4466-af85-793a66c08476">

**Closed as completed by ssin1901** 2024-10-09 11:44 UTC
Labels: bug
