### ISSUE TITLE
Discussion: Duplicated line on moderation reason pop-up 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1000] opened 2024-03-14 12:09 UTC
Why clicking 'Why' on moderated argument: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b3bc929d-4c1e-4479-ae89-306a6a1630d9)

**Comment by ilmartyrk** [comment] 2024-03-14 19:31
Closing, duplicate of https://github.com/citizenos/citizenos-fe/issues/999

**Closed as completed by ilmartyrk** 2024-03-14 19:31 UTC
Labels: bug, Redesign
